/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hackschool.mol.ui;

import com.hackschool.model.EquationReader;
import com.hackschool.ui.mol;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author teohzinean
 */
public class ratioEquation extends javax.swing.JFrame {

    /**
     * Creates new form ratioEquation
     */
    public ratioEquation() {
        initComponents();
        getContentPane().setBackground(new Color(61,165,217));
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        StoichiometryCalclator = new javax.swing.JLabel();
        ByTeamWriteCodes = new javax.swing.JLabel();
        Icon = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        enterButton = new javax.swing.JButton();
        calculate2 = new javax.swing.JLabel();
        calculate6 = new javax.swing.JLabel();
        enterEquation = new javax.swing.JTextField();
        calculate7 = new javax.swing.JLabel();
        calculate8 = new javax.swing.JLabel();
        box1 = new javax.swing.JTextField();
        box2 = new javax.swing.JTextField();
        calculate9 = new javax.swing.JLabel();
        calculate10 = new javax.swing.JLabel();
        box3 = new javax.swing.JTextField();
        type = new javax.swing.JComboBox<>();
        typeFind = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(61, 165, 217));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StoichiometryCalclator.setFont(new java.awt.Font("Nanum Gothic", 1, 24)); // NOI18N
        StoichiometryCalclator.setForeground(new java.awt.Color(255, 255, 255));
        StoichiometryCalclator.setText("Stoichiometry Calculator");
        header.add(StoichiometryCalclator, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 20, -1, -1));

        ByTeamWriteCodes.setBackground(new java.awt.Color(255, 255, 255));
        ByTeamWriteCodes.setFont(new java.awt.Font("Nanum Gothic", 1, 14)); // NOI18N
        ByTeamWriteCodes.setForeground(new java.awt.Color(255, 255, 255));
        ByTeamWriteCodes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ByTeamWriteCodes.setText("By team WriteCodes");
        header.add(ByTeamWriteCodes, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 52, -1, -1));

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon.png"))); // NOI18N
        header.add(Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 20, 53, -1));

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 94));

        mainPanel.setBackground(new java.awt.Color(61, 165, 217));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setBackground(new java.awt.Color(61, 165, 217));
        back.setForeground(new java.awt.Color(61, 165, 217));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                backMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        mainPanel.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 41));

        enterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/enterButton_Default.png"))); // NOI18N
        enterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                enterButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                enterButtonMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enterButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enterButtonMouseEntered(evt);
            }
        });
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });
        mainPanel.add(enterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 86, 42));

        calculate2.setBackground(new java.awt.Color(255, 255, 255));
        calculate2.setFont(new java.awt.Font("Nanum Gothic", 1, 36)); // NOI18N
        calculate2.setForeground(new java.awt.Color(255, 255, 255));
        calculate2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        calculate2.setText("Calculate Mol");
        mainPanel.add(calculate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 20, 240, -1));

        calculate6.setBackground(new java.awt.Color(255, 255, 255));
        calculate6.setFont(new java.awt.Font("Nanum Gothic", 1, 24)); // NOI18N
        calculate6.setForeground(new java.awt.Color(255, 255, 255));
        calculate6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        calculate6.setText("With Balanced Equation");
        mainPanel.add(calculate6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        enterEquation.setFont(new java.awt.Font("Nanum Gothic", 1, 24)); // NOI18N
        mainPanel.add(enterEquation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 370, 50));

        calculate7.setBackground(new java.awt.Color(255, 255, 255));
        calculate7.setFont(new java.awt.Font("Nanum Gothic", 1, 18)); // NOI18N
        calculate7.setForeground(new java.awt.Color(255, 255, 255));
        calculate7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        calculate7.setText("Enter Balanced Equation:");
        mainPanel.add(calculate7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        calculate8.setBackground(new java.awt.Color(255, 255, 255));
        calculate8.setFont(new java.awt.Font("Nanum Gothic", 1, 18)); // NOI18N
        calculate8.setForeground(new java.awt.Color(255, 255, 255));
        calculate8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        calculate8.setText("Find mol of : ");
        mainPanel.add(calculate8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        box1.setFont(new java.awt.Font("Nanum Gothic", 1, 24)); // NOI18N
        box1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box1ActionPerformed(evt);
            }
        });
        mainPanel.add(box1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 100, 50));

        box2.setFont(new java.awt.Font("Nanum Gothic", 1, 24)); // NOI18N
        mainPanel.add(box2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 100, 50));

        calculate9.setBackground(new java.awt.Color(255, 255, 255));
        calculate9.setFont(new java.awt.Font("Nanum Gothic", 1, 18)); // NOI18N
        calculate9.setForeground(new java.awt.Color(255, 255, 255));
        calculate9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        calculate9.setText("mol of");
        mainPanel.add(calculate9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        calculate10.setBackground(new java.awt.Color(255, 255, 255));
        calculate10.setFont(new java.awt.Font("Nanum Gothic", 1, 18)); // NOI18N
        calculate10.setForeground(new java.awt.Color(255, 255, 255));
        calculate10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        calculate10.setText("Fill in given info :");
        mainPanel.add(calculate10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        box3.setFont(new java.awt.Font("Nanum Gothic", 1, 24)); // NOI18N
        mainPanel.add(box3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 160, 50));

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reactant", "Product" }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        mainPanel.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 110, -1));

        typeFind.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reactant", "Product" }));
        typeFind.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeFindItemStateChanged(evt);
            }
        });
        typeFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeFindActionPerformed(evt);
            }
        });
        mainPanel.add(typeFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 390, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMousePressed
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource("/Images/back_pressed.png"));
        back.setIcon(ii);
    }//GEN-LAST:event_backMousePressed

    private void backMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseReleased
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource("/Images/back_hover.png"));
        back.setIcon(ii);
    }//GEN-LAST:event_backMouseReleased

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource("/Images/back.png"));
        back.setIcon(ii);
    }//GEN-LAST:event_backMouseExited

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource("/Images/back_hover.png"));
        back.setIcon(ii);
    }//GEN-LAST:event_backMouseEntered

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        mol goMol = new mol();
        goMol.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void enterButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterButtonMousePressed
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource("/Images/enterButton_Pressed.png"));
        enterButton.setIcon(ii);
    }//GEN-LAST:event_enterButtonMousePressed

    private void enterButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterButtonMouseReleased
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource("/Images/enterButton_Hover.png"));
        enterButton.setIcon(ii);
    }//GEN-LAST:event_enterButtonMouseReleased

    private void enterButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterButtonMouseExited
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource("/Images/enterButton_Default.png"));
        enterButton.setIcon(ii);
    }//GEN-LAST:event_enterButtonMouseExited

    private void enterButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterButtonMouseEntered
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource("/Images/enterButton_Hover.png"));
        enterButton.setIcon(ii);
    }//GEN-LAST:event_enterButtonMouseEntered

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        // TODO add your handling code here:
        
        String element = box2.getText().toString();
        String elementFind = box3.getText().toString();
        String elementType = type.getSelectedItem().toString();
        String elementTypeFind = typeFind.getSelectedItem().toString();
        
        
        if (enterEquation.getText().contains(".*\\d.*")) {
            
            JOptionPane.showMessageDialog(this, "Format of Balanced Equation is : 5reactant + 2reactant = 3product");
            return;
        }
        
        String equation = enterEquation.getText().toString();
        if ((enterEquation.getText().isEmpty()) || (box1.getText().isEmpty()) || (box2.getText().isEmpty()) || (box3.getText().isEmpty())) {
            JOptionPane.showMessageDialog(this, "Format of Balanced Equation is : 5reactant + 2reactant = 3product");
            return;
        }
        
        if (!box1.getText().matches(".*\\d.*") || box1.getText().matches(".*[a-zA-Z]+.*")) {
            JOptionPane.showMessageDialog(this, "Enter mol of given info (This is the mol of the reactant/product you have)");
            return;
        }
        
        double givenMol = Double.parseDouble(box1.getText());
        
        double coefficient1;
        double coefficient2;
        EquationReader eqR = new EquationReader(equation);
        if (elementType.equals("Product")) {
            coefficient1 = eqR.getProductCoefficient(element);
        } else {
            coefficient1 = eqR.getReactantCoefficient(element);
        }
        
        if (elementTypeFind.equals("Product")) {
            coefficient2 = eqR.getProductCoefficient(elementFind);
        } else {
            coefficient2 = eqR.getReactantCoefficient(elementFind);
        }
        
        if (coefficient1 == -1) {
            JOptionPane.showMessageDialog(this, "Are you sure " + element +  " is a " + elementType + "? Please try again");
            return;
        } else if(coefficient2 == -1){
            JOptionPane.showMessageDialog(this, "Are you sure " + elementFind + " is a " + elementTypeFind + "? Please try again");
            return;
        } 
        
        double a1 = givenMol * coefficient2;
        System.out.println(a1);
        double ans = (a1 / coefficient1);
        System.out.println(ans);
        double mol = (givenMol * coefficient2) / coefficient1;        
        JOptionPane.showMessageDialog(this, elementTypeFind + " " + elementFind + " = " + ans + " mol");
        
        
    }//GEN-LAST:event_enterButtonActionPerformed

    private void typeFindItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeFindItemStateChanged
        
    }//GEN-LAST:event_typeFindItemStateChanged

    private void box1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box1ActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    private void typeFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeFindActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ratioEquation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ratioEquation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ratioEquation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ratioEquation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ratioEquation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ByTeamWriteCodes;
    private javax.swing.JLabel Icon;
    private javax.swing.JLabel StoichiometryCalclator;
    private javax.swing.JButton back;
    private javax.swing.JTextField box1;
    private javax.swing.JTextField box2;
    private javax.swing.JTextField box3;
    private javax.swing.JLabel calculate10;
    private javax.swing.JLabel calculate2;
    private javax.swing.JLabel calculate6;
    private javax.swing.JLabel calculate7;
    private javax.swing.JLabel calculate8;
    private javax.swing.JLabel calculate9;
    private javax.swing.JButton enterButton;
    private javax.swing.JTextField enterEquation;
    private javax.swing.JPanel header;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JComboBox<String> typeFind;
    // End of variables declaration//GEN-END:variables
}
