/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hackschool.ui;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author teohzinean
 */
public class homePage extends javax.swing.JFrame {

    /**
     * Creates new form homePage
     */
    public homePage() {
        initComponents();
        getContentPane().setBackground(new Color(61,165,217));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        StoichiometryCalclator = new javax.swing.JLabel();
        ByTeamWriteCodes = new javax.swing.JLabel();
        Icon = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        enterButton = new javax.swing.JButton();
        optionCalculation = new javax.swing.JComboBox<>();
        calculate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(61, 165, 217));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StoichiometryCalclator.setFont(new java.awt.Font("Nanum Gothic", 1, 24)); // NOI18N
        StoichiometryCalclator.setForeground(new java.awt.Color(255, 255, 255));
        StoichiometryCalclator.setText("Stoichiometry Calculator");
        header.add(StoichiometryCalclator, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 20, -1, -1));

        ByTeamWriteCodes.setBackground(new java.awt.Color(255, 255, 255));
        ByTeamWriteCodes.setFont(new java.awt.Font("Nanum Gothic", 1, 14)); // NOI18N
        ByTeamWriteCodes.setForeground(new java.awt.Color(255, 255, 255));
        ByTeamWriteCodes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ByTeamWriteCodes.setText("By team WriteCodes");
        header.add(ByTeamWriteCodes, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 52, -1, -1));

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon.png"))); // NOI18N
        header.add(Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 20, -1, -1));

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 391, 94));

        mainPanel.setBackground(new java.awt.Color(61, 165, 217));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/enterButton_Default.png"))); // NOI18N
        enterButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        enterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                enterButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                enterButtonMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enterButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enterButtonMouseEntered(evt);
            }
        });
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });
        mainPanel.add(enterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 86, 42));

        optionCalculation.setFont(new java.awt.Font("Nanum Gothic", 1, 18)); // NOI18N
        optionCalculation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Mol", "Concentration", "Volume", "Yield", "Purity" }));
        mainPanel.add(optionCalculation, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 200, 40));

        calculate.setBackground(new java.awt.Color(255, 255, 255));
        calculate.setFont(new java.awt.Font("Nanum Gothic", 1, 24)); // NOI18N
        calculate.setForeground(new java.awt.Color(255, 255, 255));
        calculate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        calculate.setText("Calculate :");
        mainPanel.add(calculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 200, 40));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 391, 515));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterButtonMouseEntered
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource("/Images/enterButton_Hover.png"));
        enterButton.setIcon(ii);
    }//GEN-LAST:event_enterButtonMouseEntered

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        // TODO add your handling code here:
        String option = optionCalculation.getSelectedItem().toString();
        
        if (option.equals("Mol")) {
            mol molFrame = new mol();
            molFrame.setVisible(true);
            this.setVisible(false);
            this.dispose();
        }
        else
        if (option.equals("Concentration")) {
            Concentration conFrame = new Concentration();
            conFrame.setVisible(true);
            this.setVisible(false);
            this.dispose();
        }
        else
        if (option.equals("Volume")) {
            Volume volFrame = new Volume();
            volFrame.setVisible(true);
            this.setVisible(false);
            this.dispose();
        }
        else
        if (option.equals("Yield")) {
            Yield goYield = new Yield();
            goYield.setVisible(true);
            this.setVisible(false);
            this.dispose();
        }
        else
        if (option.equals("Purity")) {
            Purity goPurity = new Purity();
            goPurity.setVisible(true);
            this.setVisible(false);
            this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please select an option");
        }
    }//GEN-LAST:event_enterButtonActionPerformed

    private void enterButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterButtonMouseExited
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource("/Images/enterButton_Default.png"));
        enterButton.setIcon(ii);
    }//GEN-LAST:event_enterButtonMouseExited

    private void enterButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterButtonMousePressed
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource("/Images/enterButton_Pressed.png"));
        enterButton.setIcon(ii);
    }//GEN-LAST:event_enterButtonMousePressed

    private void enterButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterButtonMouseReleased
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource("/Images/enterButton_Hover.png"));
        enterButton.setIcon(ii);
    }//GEN-LAST:event_enterButtonMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ByTeamWriteCodes;
    private javax.swing.JLabel Icon;
    private javax.swing.JLabel StoichiometryCalclator;
    private javax.swing.JLabel calculate;
    private javax.swing.JButton enterButton;
    private javax.swing.JPanel header;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JComboBox<String> optionCalculation;
    // End of variables declaration//GEN-END:variables
}
